//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathTrap {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MathTrapResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MathTrapResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathTrap.MathTrapResources", typeof(MathTrapResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MAIN.
        /// </summary>
        internal static string help_Button1 {
            get {
                return ResourceManager.GetString("help_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to save score?.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a High Score.
        /// </summary>
        internal static string label32 {
            get {
                return ResourceManager.GetString("label32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date.
        /// </summary>
        internal static string label33 {
            get {
                return ResourceManager.GetString("label33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right.
        /// </summary>
        internal static string label34 {
            get {
                return ResourceManager.GetString("label34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fail.
        /// </summary>
        internal static string label35 {
            get {
                return ResourceManager.GetString("label35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setting Game.
        /// </summary>
        internal static string label36 {
            get {
                return ResourceManager.GetString("label36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operator.
        /// </summary>
        internal static string label37 {
            get {
                return ResourceManager.GetString("label37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Operator: .
        /// </summary>
        internal static string label38 {
            get {
                return ResourceManager.GetString("label38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Operator Bonus: .
        /// </summary>
        internal static string label39 {
            get {
                return ResourceManager.GetString("label39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fail.
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Life.
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a NEW.
        /// </summary>
        internal static string main_Button1 {
            get {
                return ResourceManager.GetString("main_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RESUME.
        /// </summary>
        internal static string main_Button2 {
            get {
                return ResourceManager.GetString("main_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HELP.
        /// </summary>
        internal static string main_Button3 {
            get {
                return ResourceManager.GetString("main_Button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SCORES.
        /// </summary>
        internal static string main_Button4 {
            get {
                return ResourceManager.GetString("main_Button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INVIO.
        /// </summary>
        internal static string math_Button1 {
            get {
                return ResourceManager.GetString("math_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CANCEL.
        /// </summary>
        internal static string math_Button2 {
            get {
                return ResourceManager.GetString("math_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EXIT.
        /// </summary>
        internal static string math_Button3 {
            get {
                return ResourceManager.GetString("math_Button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SKIP.
        /// </summary>
        internal static string math_Button4 {
            get {
                return ResourceManager.GetString("math_Button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SETTINGS.
        /// </summary>
        internal static string math_Button5 {
            get {
                return ResourceManager.GetString("math_Button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string save_Button1 {
            get {
                return ResourceManager.GetString("save_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string save_Button2 {
            get {
                return ResourceManager.GetString("save_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MAIN.
        /// </summary>
        internal static string score_Button1 {
            get {
                return ResourceManager.GetString("score_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CLEAR.
        /// </summary>
        internal static string score_Button2 {
            get {
                return ResourceManager.GetString("score_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RETURN.
        /// </summary>
        internal static string setting_Button1 {
            get {
                return ResourceManager.GetString("setting_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SAVE.
        /// </summary>
        internal static string setting_Button2 {
            get {
                return ResourceManager.GetString("setting_Button2", resourceCulture);
            }
        }
    }
}
